### ISSUE TITLE
作者大大，咋个运行出来呀，求指导

### ISSUE THREAD

**Issue by dragonkc60** [troubadour-hell/sessdsa_homework-score#2]

**Comment by troubadour-hell** [comment]
django写的，你搜一下django教程看一看就懂了

**Comment by dragonkc60** [comment]
请问添加了manage.py文件后运行了python manage.py runserver命令，报错了，是缺了数据库嘛，
![image](https://user-images.githubusercontent.com/93192391/218355430-00165407-dea8-4fb7-8c2e-2b69c392ee67.png)

**Comment by dragonkc60** [comment]
回了，感动！请问添加了manage.py文件后运行了python manage.py runserver命令，报错了，是缺了数据库嘛，
![image](https://user-images.githubusercontent.com/93192391/218355430-00165407-dea8-4fb7-8c2e-2b69c392ee67.png)

**Comment by troubadour-hell** [comment]
你这截图看不出来，关键信息在更上面，建议你了解下python报错信息的结构，自己掌握下调试方法
